[build]
  command = "npm run build"
  functions = "functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["pg-native"]

[dev]
  command = "npm start"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
